### ISSUE TITLE
Crash when trying to open inventory (1.19.2)

### ISSUE THREAD

**Issue by leyxcx** [AlphaMode/PortableTables#3]
[crash-2022-11-13_00.08.12-client.txt](https://github.com/AlphaMode/PortableTables/files/9994798/crash-2022-11-13_00.08.12-client.txt)

**Comment by AlphaMode** [comment]
Are you using the 1.18.2 build by any chance I accidentally marked it for 1.19.2?

**Comment by leyxcx** [comment]
ah yes, don't know how I missed that in the jar name lmao.
