### ISSUE TITLE
Forced out of server on clicking Crafting Table button on inventory GUI

### ISSUE THREAD

**Issue by ChromaPIE** [AlphaMode/PortableTables#7]
Using Fabric 1.19.2
Related log in server console: https://mclo.gs/TDhITbP

**Comment by AlphaMode** [comment]
What minecraft version are you using?

**Comment by ChromaPIE** [comment]
Fabric 1.19.2, as mentioned above.

**Comment by AlphaMode** [comment]
Can you see if this fixes it? https://drive.google.com/file/d/1iY33BKCw0H5WaxmSSq9L1kLVCrQ0tEst/view?usp=sharing

**Comment by ChromaPIE** [comment]
~~i'll try it right away. besides is it intended that portable furnace and its variants don't produce exp?~~
nvm just saw #4

**Comment by AlphaMode** [comment]
> i'll try it right away. besides is it intended that portable furnace and its variants don't produce exp?

Its a internal debate of mine, ether I allow them to give xp or don't. Another option I thought of is to give reduced xp. I even made a issue about it here https://github.com/AlphaMode/PortableTables/issues/4 incase you have any opinions

**Comment by ChromaPIE** [comment]
had a test. issue fixed

**Comment by AlphaMode** [comment]
https://modrinth.com/mod/ptables/version/NFiiwBkx fixed in 2.2
