### ISSUE TITLE
Conflict with other mods that use MixinExtras

### ISSUE THREAD

**Issue by AndreAugustoDev** [AlphaMode/PortableTables#9]
Minecraft 1.19.2
Forge 43.2.6
With this mod, isn't possible to start game, and throw exceptions from mods using MixinExtras
[latest.log](https://mclo.gs/gLYIHPV)
[debug.log](https://mclo.gs/vobu8aN)

**Comment by AlphaMode** [comment]
Thanks, I can check this out in the morning. It might be possible I'm using a outdated mixin extras version.
